### ISSUE TITLE
Pins open link with Safari, not my default Arc browser

### ISSUE THREAD

**Issue by QIanGua** [SKaplanOfficial/Raycast-Pins#1]
Hi, @SKaplanOfficial I find Pins is a great extension to quick open something. Is it able to set open with app by myself?
![CleanShot 2023-09-24 at 22 30 30@2x](https://github.com/SKaplanOfficial/Raycast-Pins/assets/7362290/57fb778c-ffc0-404f-a5c4-8d00e7d3989f)

**Comment by SKaplanOfficial** [comment]
Hm, there seems to be a bug here. The 'Open With' field should allow you to select a browser in this case. Will have a fix in an update this week.

**Comment by SKaplanOfficial** [comment]
Fixed in the next release, awaiting approval. See Raycast/extensions#9055.
