### ISSUE TITLE
After Edit Pin all Pins are delete 

### ISSUE THREAD

**Issue by Philnue** [SKaplanOfficial/Raycast-Pins#4]
After edit pin submit form the windows goes back with the message successfull. But the pins just got deleted :(

I updated to the latest version but still not working for me

**Comment by SKaplanOfficial** [comment]
Hmm, it might be an issue with missing data from before the update. I'll look into it!

**Comment by SKaplanOfficial** [comment]
Do you still have this issue on the latest version pushed out this morning?

**Comment by Philnue** [comment]
Looking good, I will test it the days
