### ISSUE TITLE
Open file by shell

### ISSUE THREAD

**Issue by VaJoy** [SKaplanOfficial/Raycast-Pins#8]
I tryna use TextEdit to open a selected file in Finder by running the following placeholder:

```
{{shell: open -a TextEdit {{selectedFile}}}}
```

But this placeholder doesn't work, how can I fix it?

**Comment by VaJoy** [comment]
By the way I've try all of these:

```
{{copy:file path:{{selectedFile()}} }}

{{copy:file path:{{selectedFile}} }}

{{copy:file path:{{selectedFile()}}}}

{{copy:file path:{{selectedFile}}}}
```

But none works (get empty from `selectedFile`).😭

**Comment by nrome-n** [comment]
Same issue all the place holders i tried are returning empty ex: cd {{currentDirectory}}

**Comment by SKaplanOfficial** [comment]
There was a problem with `{{selectedFiles}}` and `{{currentDirectory}}` where they weren't getting replaced correctly (unexpectedly getting replaced with an object instead of a string). Should be fixed once https://github.com/raycast/extensions/pull/13118 passes review.
